### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by pieterhuijgen**
port should be 4998 instead of 4999. Can someone please generate a new build for osx? thanks!

### CODE REVIEW

**Comment by cxselph** [comment]
The module has been functional and I have personally been using it regularly with no issues for months. What equipment are you having trouble connecting to. Maybe a baud rate mismatch with gear?

4. Command and Data Structure
Communication with the iTach is accomplished by opening a TCP socket on Port 4998. All commands and data, **with the exception of serial (RS232) data,** are communicated through Port 4998. Port 4998 is iTach API Specification used for such things as iTach status, IR data, relay operation, and reading digital input states. All information, with the exception of serial data, is communicated by comma delimited ASCII text strings terminated by a carriage return ( ). ↵
**Serial data is communicated via Ports 4999 and above.** The serial connection in module 1 will
communicate over Port 4999. Serial connections in the next lowest module will communicate over Port 5000, and so on (i.e. 1:4999, 2:5000, 3:5001, etc.).

**Comment by pieterhuijgen** [comment]
Hi!

Thanks for your swift reply. 
When I use port 4998 in itest I’m able to send the commands, also cross checked with widget designer by Christie. Port 4999 for some reason doesn’t work. 

Met vriendelijke groet / best regards,

Pieter Huijgen


PROSIGN technical production management
Generaal Winkelmanstraat 180
3769 EH Soesterberg
T: (+31)6 1037 7805
E: info@prosign.nl

| event & production management | interactive visuals & show control | 
| www.prosign.nl | www.pandorasbox.nl | www.lichtontwerp.com |

Sent from my iPhone

**Comment by cxselph** [comment]
Can you verify that you are using an itach IP2SL? I just tested with my IP2SL and itest as well and it failed on 4998. Just for giggles, I tried 4998 in my dev environment and it failed until I put it back to port 4999. I certainly don't want to break the module for everyone else. I have attached screenshots from itest.

**Comment by pieterhuijgen** [comment]
Hi,

I think you’re right on the port number as I need to use port 4999 in iTest in order to make it work, so the problem should be somewhere else.
I’m definitely using the IP2SL, so I will continue my search… The command is as simple as 50701% , nothing fancy...

**Comment by cxselph** [comment]
My only thought would be to make sure the serial settings in the itach match what the documentation of your device says it should be. 
settings

**Comment by pieterhuijgen** [comment]
Already double checked that, and it works properly with itest. Maybe the % in the command gives an error?

**Comment by cxselph** [comment]
This probably isnt it, but worth looking at. I turned on the multiple ports option in the serial settings so that more than one device or software app can talk to the IP2SL at a time. 
ports

**Comment by cxselph** [comment]
@pieterhuijgen I am going to close this pull request. Any luck?

**Comment by pieterhuijgen** [comment]
Hi,

Unfortunately I’m only able to test in a couple of weeks. I’ll let you know..

Met vriendelijke groet / best regards,

Pieter Huijgen


PROSIGN technical production management
Generaal Winkelmanstraat 180
3769 EH Soesterberg
T: (+31)6 1037 7805
E: info@prosign.nl

| event & production management | interactive visuals & show control | 
| www.prosign.nl | www.pandorasbox.nl | www.lichtontwerp.com |

Sent from my iPhone

**Pull request closed without merging**
